;        1         2         3         4         5         6         7
;234567890123456789012345678901234567890123456789012345678901234567890
;=====================================================================
;
; constants.inc
;
; This header file contains constant symbols.
;
;=====================================================================

; System call numbers
SYSCALL_EXIT          equ    1 ;exit the program

; Program constants
ELEMENTS_T001         equ    3 ;number of columns in matrix X
ELEMENTSIZE_T001      equ    4 ;size of a column in matrix X
